### ISSUE TITLE
Plans for Python3 support?

### ISSUE THREAD

**Issue by kennydo** [Yelp/kafka-utils#114]
`kafka-utils` is a great tool, but our stack is all python3, and I'd love to integrate it into our existing tooling.

Are there any plans for python3 support? Would you mind if I submitted a PR (if there hasn't been any work on this already)?

**Comment by ny2ko** [comment]
We currently aren't planning to add support but feel free to submit a PR

**Comment by jparkie** [comment]
@kennydo. Yesterday, I asked the team who owns kafka-utils if I could tackle this as a dependency for one of my projects. If you would like, you can sync with me on this.

**Comment by kennydo** [comment]
Hi @jparkie ! I've already started working on a branch to do this and have gotten `stats` and `rebalance` working: https://github.com/Yelp/kafka-utils/compare/master...kennydo:kedo-python34?expand=1

I haven't tested the other commands but based on the test failures in Travis, there is still more work to do.

How far have you gotten in this task?

**Comment by jparkie** [comment]
@kennydo - That's awesome! I started yesterday. I am thinking of using http://python-future.org/index.html because we currently support py27. I am thinking of removing Fabric as a dependency because Fabric can cause the kafka-rolling-restart script to flake. The DistSys team told me they were thinking of replacing Fabric with Paramiko (which Fabric abstracts) instead. Paramiko is currently used in https://github.com/Yelp/kafka-utils/blob/master/kafka_utils/kafka_corruption_check/main.py, so I'm going to update the kafka-rolling-restart script to be similar.

**Comment by kennydo** [comment]
Another Yelper pointed out a few issues with future (https://github.com/Yelp/yelp_clog/pull/18#issue-143837308), which is why I went with six instead.

I just made a PR with (mostly) automated `six`-ification of the existing code and structure:
https://github.com/Yelp/kafka-utils/pull/117

I think the addition of python3 support can happen in parallel with those replacements and updates.

**Comment by jparkie** [comment]
@kennydo That sounds good! I'm testing my refactor of the kafka-rolling-restart script today.

**Comment by jparkie** [comment]
@kennydo https://github.com/Yelp/kafka-utils/pull/121 removes Fabric as a dependency. After your PR and mine gets merged, this repository should be py3 compatible. :)

**Comment by kennydo** [comment]
Merged https://github.com/Yelp/kafka-utils/pull/117 so I'll close this issue!
