### ISSUE TITLE
ImportErrors - Structure of dependent kafka-python package changed

### ISSUE THREAD

**Issue by suknuk** [Yelp/kafka-utils#199]
The code-structure of the python-kafka package has changed which is causing some parts of this package to import classes with the wrong path. This can be seen in [util/offsets.py](https://github.com/Yelp/kafka-utils/blob/master/kafka_utils/util/offsets.py) file which imports error classes from _kafka.structs_. These are however not anymore in the structus.py file, but in the errors.py file (as can be seen in this [commit](https://github.com/dpkp/kafka-python/commit/221f56d8a05cdc2d37f85018e4af352b4b2a95c5#diff-d44163af6a47884d5684568142e14ac7R49))

**Comment by jeffwidman** [comment]
Sorry about this. I'm one of the upstream maintainers of `kafka-python`. 

Did you get a chance to grab a full stacktrace of the exception? 

I am not understanding why the imports broke because as you noted in #200 we kept a wildcard import to support legacy imports just like this. So very curious what about the python import machinery we did not understand when we made this upstream change.

**Comment by jeffwidman** [comment]
Also, @88manpreet it sounds like this issue can be closed per your comment in #200
